language: ruby
rvm:
  - 2.4
cache: bundler
sudo: false
dist: trusty

script:
  - bundle install
  - bundle exec rubocop --version
  - travis_wait 60 bundle exec rubocop
  - bundle exec foodcritic --version
  - travis_wait 60 bundle exec foodcritic . --exclude spec
  - travis_wait 60 bundle exec rspec spec
before_install:
  - openssl aes-256-cbc -K $encrypted_22c7dcef7ed5_key -iv $encrypted_22c7dcef7ed5_iv -in .travis/supermarket.pem.enc -out .travis/supermarket.pem -d
deploy:
  provider: script
  script: rvm use 2.4 do bash -c 'bundle install && bundle exec knife supermarket share kill-switch -o .. --config-option user=mkulka --config-option client_key=.travis/supermarket.pem'
  skip_cleanup: true
  on:
    tags: true
